version: "3.7"

services:
  database:
    image: mysql:5.7
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: dohee
      MYSQL_PASSWORD: doheepassword
      MYSQL_DATABASE: plays_db
    networks:
      - spotifynet

  myapp:
    image: dohee/spotify-auto:latest
    container_name: myapp
    restart: always
    depends_on:
      - database
    ports:
      - "80:80"
    networks:
      - spotifynet

networks:
  spotifynet:
    driver: bridge